# P0-1: regenerate build_buildinfo.h at BUILD time (not qmake time) so an incremental build can
# never carry a stale embedded SHA. Write-if-different so it only forces a recompile when the
# commit/dirty-state actually changes. ASCII-only by design.
param(
    [Parameter(Mandatory = $true)][string]$SrcRoot,
    [Parameter(Mandatory = $true)][string]$OutHeader
)
$ErrorActionPreference = 'Continue'
function GitOut([string[]]$a) { try { (& git -C $SrcRoot @a 2>$null) -join "`n" } catch { '' } }

$sha = (GitOut @('rev-parse','HEAD')).Trim()
if (-not $sha) { $sha = 'unknown' }
$porcelain = GitOut @('status','--porcelain')
$dirty = if ($porcelain -and $porcelain.Trim().Length -gt 0) { 1 } else { 0 }
$desc = (GitOut @('describe','--always','--dirty','--abbrev=40')).Trim()
if (-not $desc) { $desc = $sha }
$utc = [DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ')

$body = @"
/* AUTO-GENERATED by tools/gen-buildinfo.ps1 at build time. Do not edit; do not commit. */
#ifndef MLVAPP_BUILD_BUILDINFO_H
#define MLVAPP_BUILD_BUILDINFO_H
/* MLVAPP_GIT_SHA may also arrive via -D from the .pro; guard to avoid redefinition. The
   build-time value here is authoritative for the dirty flag + build time. */
#ifndef MLVAPP_GIT_SHA
#define MLVAPP_GIT_SHA "$sha"
#endif
#define MLVAPP_BUILD_SHA "$sha"
#define MLVAPP_GIT_DIRTY $dirty
#define MLVAPP_GIT_DESCRIBE "$desc"
#define MLVAPP_BUILD_TIME_UTC "$utc"
#endif
"@

$existing = if (Test-Path -LiteralPath $OutHeader) { Get-Content -LiteralPath $OutHeader -Raw } else { '' }
if ($existing -ne $body) {
    Set-Content -LiteralPath $OutHeader -Value $body -Encoding ASCII
    Write-Host "[gen-buildinfo] wrote $OutHeader  sha=$sha dirty=$dirty"
} else {
    Write-Host "[gen-buildinfo] unchanged  sha=$sha dirty=$dirty"
}
