name: macOS Intel Release

on:
  workflow_dispatch:
    branches: [ "master" ]

permissions:
  contents: read

env:
  SOURCE_DIR:   ${{ github.workspace }}/platform
  QTDIR:        /usr/local/opt/qt@5/bin
  ARTIFACT:     ${{ github.workspace }}/platform/build/MLV\ App.dmg

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      with:
        persist-credentials: false

    - name: Install llvm & Qt & OpenSSL
      continue-on-error: true
      uses: ConorMacBride/install-package@3e7ad059e07782ee54fa35f827df52aae0626f30 # v1.1.0
      with:
        brew: llvm qt5 openssl
              
    - name: Create build directory
      run:  mkdir ${{ env.SOURCE_DIR }}/build

    - name: Build
      working-directory: ${{ env.SOURCE_DIR }}/build
      run:  |
            ${{ env.QTDIR }}/qmake -r ${{ env.SOURCE_DIR }}/qt/MLVApp.pro
            make -j8
            ls -al
            ${{ env.QTDIR }}/macdeployqt MLV\ App.app -dmg

    - name: Save build artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: MLVApp macOS Intel
        path: ${{ env.ARTIFACT }}
